2024-10-24 12:04:34,010 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:04:37,129 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:04:41,205 ERROR: Unhandled exception: Error creating backref 'items_factura' on relationship 'ItemFactura.item': property of that name exists on mapper 'Mapper[InventarioItem(items_inventario)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:17:39,243 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:17:44,676 ERROR: Unhandled exception: Multiple classes found for path "MovimientoInventario" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:18:47,626 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:18:54,613 ERROR: Unhandled exception: Multiple classes found for path "ItemFactura" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:19:36,856 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:19:43,971 ERROR: Unhandled exception: Multiple classes found for path "ItemFactura" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:22:17,196 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:23:14,422 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:23:17,648 ERROR: Unhandled exception: Multiple classes found for path "ItemFactura" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:24:08,518 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:26:54,018 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:27:04,767 ERROR: Unhandled exception: Error creating backref 'items_facturas' on relationship 'ItemFactura.item': property of that name exists on mapper 'Mapper[InventarioItem(items_inventario)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:28:24,963 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:28:26,133 ERROR: Unhandled exception: Error creating backref 'items_facturas' on relationship 'ItemFactura.item': property of that name exists on mapper 'Mapper[InventarioItem(items_inventario)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:29:34,692 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:29:43,551 ERROR: Unhandled exception: Error creating backref 'factura' on relationship 'Facturacion.items': property of that name exists on mapper 'Mapper[ItemFactura(items_facturas)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:35:16,452 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:35:35,054 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:35:38,031 ERROR: Unhandled exception: Error creating backref 'item' on relationship 'InventarioItem.items_pre_factura': property of that name exists on mapper 'Mapper[ItemPreFactura(items_pre_factura)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:36:40,563 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:37:20,902 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:38:01,083 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 16:35:28,646 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:316]
2024-10-24 16:37:02,412 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:316]
2024-10-24 17:43:13,684 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 17:43:17,049 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 17:44:26,986 ERROR: Unhandled exception: Entity namespace for "campaign" has no property "user_id" [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 17:44:38,080 ERROR: Unhandled exception: 'user_id' is an invalid keyword argument for Campaign [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 17:44:38,101 ERROR: Unhandled exception: Entity namespace for "campaign" has no property "user_id" [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 21:37:09,909 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 22:07:22,830 ERROR: Error al obtener items: (psycopg2.errors.UndefinedColumn) no existe la columna items_inventario.costo
LINE 1: ...ventario.categoria AS items_inventario_categoria, items_inve...
                                                             ^

[SQL: SELECT items_inventario.id AS items_inventario_id, items_inventario.codigo AS items_inventario_codigo, items_inventario.nombre AS items_inventario_nombre, items_inventario.descripcion AS items_inventario_descripcion, items_inventario.tipo AS items_inventario_tipo, items_inventario.categoria AS items_inventario_categoria, items_inventario.costo AS items_inventario_costo, items_inventario.precio AS items_inventario_precio, items_inventario.itbis AS items_inventario_itbis, items_inventario.margen AS items_inventario_margen, items_inventario.stock AS items_inventario_stock, items_inventario.stock_minimo AS items_inventario_stock_minimo, items_inventario.stock_maximo AS items_inventario_stock_maximo, items_inventario.unidad_medida AS items_inventario_unidad_medida, items_inventario.proveedor AS items_inventario_proveedor, items_inventario.marca AS items_inventario_marca, items_inventario.fecha_creacion AS items_inventario_fecha_creacion, items_inventario.fecha_actualizacion AS items_inventario_fecha_actualizacion 
FROM items_inventario]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:36]
2024-10-25 12:19:51,891 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 12:23:25,525 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 12:32:02,148 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:14:17,686 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:14:20,404 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:21:34,147 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:21:37,787 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:37:47,584 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:37:50,119 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:42:14,272 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:43:40,968 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:43:52,836 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 15:44:04,799 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-25 16:56:33,251 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:347]
2024-10-25 21:15:42,190 ERROR: Error al obtener categorías: name 'distinct' is not defined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:266]
2024-10-26 14:55:29,885 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-26 14:57:30,738 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-26 15:00:22,751 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:411]
2024-10-27 14:09:02,566 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 14:09:06,951 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 14:41:40,266 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
