2024-10-06 01:38:45,152 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:38:46,488 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:38:58,250 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:38:59,202 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:50:53,861 ERROR: Unhandled exception: (psycopg2.errors.UndefinedColumn) no existe la columna facturacion.cliente_id
LINE 1: ...ion_id, facturacion.numero AS facturacion_numero, facturacio...
                                                             ^
HINT:  Probablemente quiera hacer referencia a la columna «facturacion.cliente».

[SQL: SELECT facturacion.id AS facturacion_id, facturacion.numero AS facturacion_numero, facturacion.cliente_id AS facturacion_cliente_id, facturacion.fecha AS facturacion_fecha, facturacion.total AS facturacion_total, facturacion.estatus AS facturacion_estatus, facturacion.fecha_creacion AS facturacion_fecha_creacion, facturacion.fecha_actualizacion AS facturacion_fecha_actualizacion 
FROM facturacion]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:51:12,425 ERROR: Unhandled exception: (psycopg2.errors.UndefinedColumn) no existe la columna facturacion.cliente_id
LINE 1: ...ion_id, facturacion.numero AS facturacion_numero, facturacio...
                                                             ^
HINT:  Probablemente quiera hacer referencia a la columna «facturacion.cliente».

[SQL: SELECT facturacion.id AS facturacion_id, facturacion.numero AS facturacion_numero, facturacion.cliente_id AS facturacion_cliente_id, facturacion.fecha AS facturacion_fecha, facturacion.total AS facturacion_total, facturacion.estatus AS facturacion_estatus, facturacion.fecha_creacion AS facturacion_fecha_creacion, facturacion.fecha_actualizacion AS facturacion_fecha_actualizacion 
FROM facturacion]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:51:21,471 ERROR: Unhandled exception: (psycopg2.errors.UndefinedColumn) no existe la columna pre_facturas.cliente_id
LINE 1: ...s_id, pre_facturas.numero AS pre_facturas_numero, pre_factur...
                                                             ^
HINT:  Probablemente quiera hacer referencia a la columna «pre_facturas.cliente».

[SQL: SELECT pre_facturas.id AS pre_facturas_id, pre_facturas.numero AS pre_facturas_numero, pre_facturas.cliente_id AS pre_facturas_cliente_id, pre_facturas.fecha AS pre_facturas_fecha, pre_facturas.total AS pre_facturas_total, pre_facturas.estatus AS pre_facturas_estatus, pre_facturas.fecha_creacion AS pre_facturas_fecha_creacion, pre_facturas.fecha_actualizacion AS pre_facturas_fecha_actualizacion 
FROM pre_facturas]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:52:56,818 ERROR: Unhandled exception: (psycopg2.errors.UndefinedColumn) no existe la columna facturacion.cliente_id
LINE 1: ...ion_id, facturacion.numero AS facturacion_numero, facturacio...
                                                             ^
HINT:  Probablemente quiera hacer referencia a la columna «facturacion.cliente».

[SQL: SELECT facturacion.id AS facturacion_id, facturacion.numero AS facturacion_numero, facturacion.cliente_id AS facturacion_cliente_id, facturacion.fecha AS facturacion_fecha, facturacion.total AS facturacion_total, facturacion.estatus AS facturacion_estatus, facturacion.fecha_creacion AS facturacion_fecha_creacion, facturacion.fecha_actualizacion AS facturacion_fecha_actualizacion 
FROM facturacion]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:53:25,019 ERROR: Unhandled exception: (psycopg2.errors.UndefinedColumn) no existe la columna facturacion.cliente_id
LINE 1: ...ion_id, facturacion.numero AS facturacion_numero, facturacio...
                                                             ^
HINT:  Probablemente quiera hacer referencia a la columna «facturacion.cliente».

[SQL: SELECT facturacion.id AS facturacion_id, facturacion.numero AS facturacion_numero, facturacion.cliente_id AS facturacion_cliente_id, facturacion.fecha AS facturacion_fecha, facturacion.total AS facturacion_total, facturacion.estatus AS facturacion_estatus, facturacion.fecha_creacion AS facturacion_fecha_creacion, facturacion.fecha_actualizacion AS facturacion_fecha_actualizacion 
FROM facturacion]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:54:15,714 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:59:51,645 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:01:17,575 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:05:42,660 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:05:53,092 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:05:53,979 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:06:07,964 ERROR: Unhandled exception: (psycopg2.errors.UndefinedColumn) no existe la columna facturacion.cliente_id
LINE 1: ...ion_id, facturacion.numero AS facturacion_numero, facturacio...
                                                             ^
HINT:  Probablemente quiera hacer referencia a la columna «facturacion.cliente».

[SQL: SELECT facturacion.id AS facturacion_id, facturacion.numero AS facturacion_numero, facturacion.cliente_id AS facturacion_cliente_id, facturacion.fecha AS facturacion_fecha, facturacion.total AS facturacion_total, facturacion.estatus AS facturacion_estatus, facturacion.fecha_creacion AS facturacion_fecha_creacion, facturacion.fecha_actualizacion AS facturacion_fecha_actualizacion 
FROM facturacion]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 02:15:57,049 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:16:47,119 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:16:56,819 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:17:07,660 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:20:41,789 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:20:52,978 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:20:59,706 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:21:15,114 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:22:00,958 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:22:02,123 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:50:47,960 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:50:49,104 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:54:52,339 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 02:56:44,937 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 09:19:46,493 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 09:19:47,780 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 09:20:00,351 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 09:20:11,850 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 09:20:23,595 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 09:20:24,678 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 09:20:32,968 ERROR: Unhandled exception: Multiple classes found for path "Item" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:315]
2024-10-06 09:20:37,727 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ItemFactura(items_factura)]'. Original exception was: Multiple classes found for path "Item" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:315]
2024-10-06 09:20:43,645 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ItemFactura(items_factura)]'. Original exception was: Multiple classes found for path "Item" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:315]
2024-10-06 14:21:15,043 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
