2024-10-27 20:23:42,139 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 20:23:45,087 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 20:37:16,494 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 20:40:37,847 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 20:47:32,646 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 20:50:15,902 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 20:53:56,128 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 20:55:00,254 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 20:55:25,854 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 21:51:58,679 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-27 22:23:10,410 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:612]
2024-10-27 22:24:36,883 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:612]
2024-10-27 22:24:49,207 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:612]
2024-10-27 22:24:56,983 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:612]
2024-10-28 01:41:09,252 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 01:41:12,190 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 01:44:44,131 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 02:08:46,710 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 02:14:27,450 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 02:26:35,222 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 02:29:45,473 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 02:40:40,618 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 12:06:06,206 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 12:06:09,483 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 12:16:17,874 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 12:16:45,669 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 12:22:10,048 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 12:23:25,473 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 13:18:51,979 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 17:01:40,357 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 17:23:03,590 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 17:28:06,539 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 17:28:10,180 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-28 23:02:34,526 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:480]
2024-10-28 23:49:26,742 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:484]
2024-10-29 00:02:49,781 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:483]
2024-10-29 00:04:04,432 ERROR: Unhandled exception: send_file() got an unexpected keyword argument 'attachment_filename' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:577]
2024-10-29 00:04:12,448 ERROR: Unhandled exception: send_file() got an unexpected keyword argument 'attachment_filename' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:577]
2024-10-29 00:08:33,527 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:485]
2024-10-29 00:12:42,053 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:474]
2024-10-29 00:12:49,046 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:474]
2024-10-29 00:15:26,108 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:523]
2024-10-29 00:28:38,642 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:490]
2024-10-29 00:28:41,524 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:490]
2024-10-29 00:34:14,336 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:490]
2024-10-29 00:37:44,012 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:550]
2024-10-29 00:50:36,161 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:564]
2024-10-29 00:50:40,392 ERROR: Unhandled exception: Could not build url for endpoint 'registro'. Did you mean 'register' instead? [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:669]
2024-10-29 00:50:42,899 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:669]
2024-10-29 00:50:42,904 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:669]
2024-10-29 00:50:42,909 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:669]
2024-10-29 00:50:42,911 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:669]
2024-10-29 00:50:42,919 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:669]
2024-10-29 00:50:45,035 ERROR: Unhandled exception: Could not build url for endpoint 'registro'. Did you mean 'register' instead? [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:669]
2024-10-29 00:50:57,310 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:550]
2024-10-29 11:54:35,980 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:583]
2024-10-29 12:28:36,080 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:638]
2024-10-29 12:31:52,132 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:638]
2024-10-29 12:32:23,313 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:638]
2024-10-29 12:32:27,119 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:638]
2024-10-29 12:45:29,639 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:638]
2024-10-29 12:55:22,156 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:570]
2024-10-29 12:56:51,197 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-29 13:50:08,445 ERROR: Unhandled exception: send_file() got an unexpected keyword argument 'attachment_filename' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:476]
2024-10-29 13:51:40,472 ERROR: Unhandled exception: send_file() got an unexpected keyword argument 'attachment_filename' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:476]
2024-10-29 14:06:52,711 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:252]
2024-10-29 14:07:41,881 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-29 16:19:32,498 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:433]
2024-10-29 16:19:35,391 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:433]
2024-10-29 16:21:00,098 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:435]
2024-10-29 16:22:07,524 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:437]
