2024-11-11 12:00:54,735 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:673]
2024-11-11 12:01:02,841 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:673]
2024-11-11 14:05:19,511 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:782]
2024-11-11 14:05:24,417 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:782]
2024-11-11 16:10:24,873 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:673]
2024-11-11 16:16:14,240 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:673]
2024-11-11 16:16:19,234 ERROR: Unhandled exception: facturacion/reporte_ventas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:782]
2024-11-11 16:17:44,557 ERROR: Unhandled exception: facturacion/reporte_ventas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:782]
2024-11-11 16:24:40,750 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:673]
2024-11-11 16:25:02,655 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:673]
2024-11-11 16:25:11,994 ERROR: Unhandled exception: facturacion/reporte-de_ventas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:782]
2024-11-11 16:26:14,105 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:673]
2024-11-11 16:28:54,561 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:673]
2024-11-11 16:50:12,972 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 16:50:20,656 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 16:50:23,755 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ItemFactura(items_facturas)]'. Original exception was: Mapper 'Mapper[InventarioItem(items_inventario)]' has no property 'facturas_items'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 16:51:47,943 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 16:51:50,354 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ItemFactura(items_facturas)]'. Original exception was: Mapper 'Mapper[InventarioItem(items_inventario)]' has no property 'facturas_items'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 16:52:33,322 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 16:55:40,641 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 16:55:47,900 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ItemFactura(items_facturas)]'. Original exception was: Mapper 'Mapper[InventarioItem(items_inventario)]' has no property 'facturas_items'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 17:01:32,644 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:01:51,531 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovimientoInventario(movimientos_inventario)]'. Original exception was: Mapper 'Mapper[Facturacion(facturacion)]' has no property 'movimientos'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 17:14:05,416 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:14:11,545 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ItemFactura(items_facturas)]'. Original exception was: Mapper 'Mapper[InventarioItem(items_inventario)]' has no property 'items_facturas'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 17:15:21,645 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:15:25,806 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovimientoInventario(movimientos_inventario)]'. Original exception was: Mapper 'Mapper[Facturacion(facturacion)]' has no property 'movimientos'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 17:17:01,255 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:17:40,372 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovimientoInventario(movimientos_inventario)]'. Original exception was: Mapper 'Mapper[Usuario(usuarios)]' has no property 'movimientos_inventario'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 17:18:54,097 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:18:59,266 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovimientoInventario(movimientos_inventario)]'. Original exception was: Error creating backref 'movimientos_inventario' on relationship 'MovimientoInventario.factura': property of that name exists on mapper 'Mapper[Facturacion(facturacion)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 17:19:57,248 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:20:31,106 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:20:34,302 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovimientoInventario(movimientos_inventario)]'. Original exception was: Mapper 'Mapper[Usuario(usuarios)]' has no property 'movimientos_inventario'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 17:22:15,772 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:22:38,379 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:22:41,000 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovimientoInventario(movimientos_inventario)]'. Original exception was: Error creating backref 'movimientos_inventario' on relationship 'MovimientoInventario.usuario': property of that name exists on mapper 'Mapper[Usuario(usuarios)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 17:24:16,552 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:24:45,209 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:24:59,490 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 17:25:22,095 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 19:23:08,959 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 19:23:25,102 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[MovimientoInventario(movimientos_inventario)]'. Original exception was: Mapper 'Mapper[Usuario(usuarios)]' has no property 'movimientos_inventario'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:703]
2024-11-11 19:24:38,495 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 19:25:05,691 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 19:25:32,766 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-11 19:26:01,938 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
